=== StarLee/lab/lab/data/data.cfg.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--数据库配置相关的dtd文件-->
<!ELEMENT data (properties,tables,mappers)>
<!ELEMENT properties (property+)>
<!ELEMENT tables (table*)>
<!ELEMENT mappers (mapper*)>
<!ELEMENT property (#PCDATA)>
<!ELEMENT table (#PCDATA)>
<!ELEMENT mapper (#PCDATA)>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST table url CDATA #REQUIRED>
<!ATTLIST mapper url CDATA #REQUIRED>

=== StarLee/lab/lab/resource/data.cfg.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 数据库的一些连接信息，映射元数据也要在这里加载过来 -->
<!DOCTYPE data SYSTEM "data.cfg.dtd">
<data>
	<properties>
		<!--  <property name="driverURL">jdbc:odbc:driver={Microsoft Access Driver (*.mdb)};DBQ=D:\\faculty2010.6.14.mdb</property>-->
		
		<!-- <property name="driverClass">sun.jdbc.odbc.JdbcOdbcDriver</property> -->
		<property name="driverURL">jdbc:mysql://localhost:3306/faculty2010</property>
		<property name="driverClass">com.mysql.jdbc.Driver</property>
		<property name="userName">root</property>
		<property name="password">server</property>
		<property name="maximum-connection-count">10</property>
	</properties>
	<tables>
		<table url="tables/Ds_college.data.xml"></table>
	</tables>
	<mappers>
		<mapper url="mapper/Ds_college.mapper.xml"></mapper>
	</mappers>
</data>
